update:
  name: Set Variable
  description: Update a variables value and/or its attributes. Must define entity or variable name.
  target:
    entity:
      integration: variable
  fields:
    value:
      name: New Value
      description: New value to set [any] (optional)
      example: 9
      selector:
        text:
    attributes:
      name: New Attributes
      description: Attributes to set or update [dictionary] (optional)
      example: {"attribute": "value"}
      selector:
        object:
    replace_attributes:
      description: Replace or merge current attributes [boolean] (optional) (default false = merge)
      example: false
      selector:
        boolean:

set_variable:
  # Description of the service
  name: Set Variable (Legacy)
  description: "Legacy service: Update a variables value and/or its attributes."
  # Different fields that your service accepts
  fields:
    # Key of the field
    variable:
      description: string (required) The name of the variable to update
      required: true
      example: test_counter
      selector:
        text:
    value:
      description: any (optional) New value to set
      example: 9
      selector:
        text:
    attributes:
      description: dictionary (optional) Attributes to set or update
      selector:
        object:
    replace_attributes:
      description: boolean (optional) Replace or merge current attributes (default false = merge)
      selector:
        boolean:
