update_sensor:
  name: Update Sensor Variable
  description: Update a Sensor Variable value and/or its attributes.
  target:
    entity:
      integration: variable
      domain: sensor
  fields:
    value:
      name: New Value
      description: New value to set [any] (optional)
      example: 9
      selector:
        text:
    attributes:
      name: New Attributes
      description: Attributes to set or update [dictionary] (optional)
      example: {"attribute": "value"}
      selector:
        object:
    replace_attributes:
      name: Replace Attributes
      description: Replace or merge current attributes [boolean] (optional) (default false = merge)
      example: false
      selector:
        boolean:

update_binary_sensor:
  name: Update Binary Sensor Variable
  description: Update a Binary Sensor Variable value and/or its attributes.
  target:
    entity:
      integration: variable
      domain: binary_sensor
  fields:
    value:
      name: New Value
      description: New value to set [boolean] (optional)
      example: false
      selector:
        boolean:
    attributes:
      name: New Attributes
      description: Attributes to set or update [dictionary] (optional)
      example: {"attribute": "value"}
      selector:
        object:
    replace_attributes:
      name: Replace Attributes
      description: Replace or merge current attributes [boolean] (optional) (default false = merge)
      example: false
      selector:
        boolean:

set_variable:
  # Description of the service
  name: Set Variable (Legacy)
  description: "Legacy service: Update a Sensor Variable value and/or its attributes. Will only work on Sensor Variables. Use one of the variable.update_ services for additional options."
  # Different fields that your service accepts
  fields:
    # Key of the field
    variable:
      description: string (required) The name of the Sensor Variable to update
      required: true
      example: test_counter
      selector:
        text:
    value:
      description: any (optional) New value to set
      example: 9
      selector:
        text:
    attributes:
      description: dictionary (optional) Attributes to set or update
      selector:
        object:
    replace_attributes:
      description: boolean (optional) Replace or merge current attributes (default false = merge)
      selector:
        boolean:

set_entity:
  name: Set Entity (Legacy)
  description: "Legacy service: Update a Sensor Variable value and/or its attributes. Will only work on Sensor Variables. Use one of the variable.update_ services for additional options."
  fields:
    entity:
      description: string (required) The entity_id of the Sensor Variable to update
      example: sensor.test_sensor
      required: true
      selector:
        entity:
          integration: variable
          domain: sensor
    value:
      description: any (optional) New value to set
      example: 9
      selector:
        text:
    attributes:
      description: dictionary (optional) Attributes to set or update
      selector:
        object:
    replace_attributes:
      description: boolean (optional) Replace or merge current attributes (default false = merge)
      selector:
        boolean:
