# Create a sensor variable with the Variable ID of `test_counter` and Initial Value of `0`

automation:
  - alias: test_counter
    initial_state: 'on'
    trigger:
      - platform: time
        seconds: '/1'
    action:
      - service: variable.update_sensor
        data:
          value: >
            {{ (states('sensor.test_counter') | int(default=0)) + 1 }}
        target:
          entity_id: sensor.test_counter
