# Create a sensor variable with the Variable ID of `keypad` and Initial Value of ``
# Create a sensor variable with the Variable ID of `keypad_timer` and Initial Value of `0`

input_boolean:
  keypad_toggle:

script:
  update_keypad:
    sequence:
      - service: variable.update_sensor
        data:
          attributes:
            last: "{{ number }}"
        target:
          entity_id: sensor.keypad
      - service: variable.update_sensor
        data:
          value: >
            {{ states('sensor.keypad') }}{{ state_attr('sensor.keypad','last') }}
        target:
          entity_id: sensor.keypad
      - service: variable.update_sensor
        data:
          value: 10
        target:
          entity_id: sensor.keypad_timer
      - service: automation.turn_on
        data:
          entity_id: automation.keypad_timer

  clear_keypad:
    sequence:
      - service: variable.update_sensor
        data:
          value: ''
        target:
          entity_id: sensor.keypad

  enter_keypad_1:
    sequence:
      - service: script.update_keypad
        data:
          number: 1

  enter_keypad_2:
    sequence:
      - service: script.update_keypad
        data:
          number: 2

  enter_keypad_3:
    sequence:
      - service: script.update_keypad
        data:
          number: 3

  enter_keypad_4:
    sequence:
      - service: script.update_keypad
        data:
          number: 4

automation:
  - alias: keypad_timer
    initial_state: 'off'
    trigger:
      - platform: time
        seconds: '/1'
    action:
      - service: variable.update_sensor
        data:
          value: >
            {{ [(states('sensor.keypad_timer') | int(default=0)) - 1, 0] | max }}
        target:
          entity_id: sensor.keypad_timer


  - alias: keypad_timeout
    trigger:
      platform: state
      entity_id: sensor.keypad_timer
      to: '0'
    action:
      - service: script.clear_keypad
      - service: automation.turn_off
        data:
          entity_id: automation.keypad_timer

  - alias: keypad_validate
    trigger:
      platform: state
      entity_id: sensor.keypad
      to: '1234'
    action:
      - service: input_boolean.toggle
        data:
          entity_id: input_boolean.keypad_toggle
      - service: script.clear_keypad
