name: prek-autofix fix

on:
  workflow_run:
    workflows: [prek-autofix]
    types: [completed]

permissions: {}

concurrency:
  group:
    prek-autofix-fix-${{ github.event.workflow_run.head_repository.full_name
    }}-${{ github.event.workflow_run.head_branch }}
  cancel-in-progress: false

jobs:
  fix:
    if: github.event.workflow_run.event == 'pull_request'
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: write
      pull-requests: write
      statuses: write

    steps:
      - uses: Snuffy2/prek-autofix/fix@ce7466280e089e648ab0ed5b5fca2095bd1e78b1 # v1 / 1.0.7
        with:
          autofix-token: ""
          source-workflow: prek-autofix
